Repository cloudera-labs/cloudera.exe, pull requests merged in 2021-11, with the labels that each got.

#64 Add missing CDF configurations
  docs/configuration.yml
Labels: documentation

#62 Add network discovery and assignment functions
  roles/platform/tasks/initialize_setup_aws.yml
  roles/platform/tasks/setup_aws_env.yml
  roles/runtime/defaults/main.yml
  roles/runtime/tasks/initialize_setup_aws.yml
  roles/runtime/tasks/initialize_setup_azure.yml
  roles/runtime/tasks/initialize_setup_gcp.yml
Labels: enhancement

#66 Add guard conditionals for CDE setup
  roles/runtime/tasks/setup_base.yml
Labels: bug

#69 Add Ubuntu 20.04 focal fossa as optional OS for dynamic inventory
  roles/infrastructure/vars/main.yml
Labels: enhancement

#48 Extensible tagging for Cloudera Experiences
  docs/design.md
  roles/runtime/tasks/initialize_base.yml
  roles/runtime/tasks/initialize_setup.yml
  roles/runtime/tasks/setup.yml
  roles/runtime/tasks/setup_aws.yml
  roles/runtime/tasks/setup_base.yml
  roles/runtime/tasks/validate_base.yml
  roles/sequence/tasks/main.yml
Labels: enhancement

#72 Fix AWS network discovery
  roles/common/defaults/main.yml
  roles/infrastructure/tasks/initialize_aws.yml
  roles/platform/defaults/main.yml
  roles/platform/tasks/initialize_setup_aws.yml
  roles/runtime/tasks/initialize_setup_aws.yml
Labels: bug

#59 Molecule test harness for platform role
  .gitignore
  requirements.txt
  roles/platform/.ansible-lint
  roles/platform/.yamllint
  roles/platform/meta/main.yml
  roles/platform/molecule/README.md
  roles/platform/molecule/default/collections.yml
  roles/platform/molecule/default/molecule.yml
  roles/platform/molecule/default/requirements.yml
  roles/platform/molecule/default/terraform/level1.tf
  roles/platform/molecule/default/terraform/storage.tf
  roles/platform/molecule/default/terraform/vars.tf
  roles/platform/molecule/default/verify.yml
  roles/platform/molecule/level0/collections.yml
  roles/platform/molecule/level0/molecule.yml
  roles/platform/molecule/level0/requirements.yml
  roles/platform/molecule/level0/terraform/level0.tf
  roles/platform/molecule/level0/terraform/storage.tf
  roles/platform/molecule/level0/terraform/vars.tf
  roles/platform/molecule/level0/verify.yml
  roles/platform/molecule/shared/cleanup.yml
  roles/platform/molecule/shared/converge.yml
  roles/platform/molecule/shared/prepare.yml
  roles/platform/tasks/setup_aws_authz.yml
  roles/runtime/molecule/README.md
  roles/runtime/molecule/default/collections.yml
  roles/runtime/molecule/default/molecule.yml
  roles/runtime/molecule/default/requirements.yml
  roles/runtime/molecule/default/terraform/level1.tf
  roles/runtime/molecule/default/terraform/storage.tf
  roles/runtime/molecule/default/terraform/vars.tf
  roles/runtime/molecule/default/verify.yml
  roles/runtime/molecule/level0/collections.yml
  roles/runtime/molecule/level0/molecule.yml
  roles/runtime/molecule/level0/requirements.yml
  roles/runtime/molecule/level0/terraform/level0.tf
  roles/runtime/molecule/level0/terraform/storage.tf
  roles/runtime/molecule/level0/terraform/vars.tf
  roles/runtime/molecule/level0/verify.yml
  roles/runtime/molecule/shared/cleanup.yml
  roles/runtime/molecule/shared/converge.yml
  roles/runtime/molecule/shared/prepare.yml
Labels: enhancement

#73 Fix reference to undefined storage tags variable
  roles/infrastructure/tasks/setup_aws_storage.yml
Labels: bug
