Repository cloudera-labs/cloudera.exe, pull requests merged in 2022-04, with the labels that each got.

#82 Support for DataFlow Deployments
  docs/configuration.yml
  roles/common/defaults/main.yml
  roles/info/tasks/main.yml
  roles/runtime/defaults/main.yml
  roles/runtime/tasks/initialize_base.yml
  roles/runtime/tasks/initialize_setup.yml
  roles/runtime/tasks/initialize_teardown.yml
  roles/runtime/tasks/setup_base.yml
  roles/runtime/tasks/teardown_base.yml
Labels: enhancement

#96 Update config docs
  docs/configuration.yml
Labels: documentation

#99 Fix dynamic inventory public IP check
  roles/infrastructure/tasks/setup_aws_compute.yml
Labels: bug

#100 Convert terraform related global variables to a dictionary
  roles/common/defaults/main.yml
Labels: enhancement

#86 Update Azure NetApp management and add NFS protocol version
  roles/common/defaults/main.yml
  roles/infrastructure/defaults/main.yml
  roles/infrastructure/tasks/setup_azure_storage.yml
  roles/infrastructure/tasks/teardown_azure_storage.yml
  roles/platform/defaults/main.yml
  roles/platform/tasks/initialize_azure.yml
  roles/runtime/defaults/main.yml
  roles/runtime/tasks/initialize_base.yml
  roles/runtime/tasks/initialize_setup_azure.yml
  roles/runtime/tasks/setup_base.yml
Labels: bug

#101 Map common__azure_sp_login_env to infra
  roles/infrastructure/defaults/main.yml
  roles/infrastructure/tasks/initialize_azure.yml
Labels: enhancement

#98 Pin collection dependencies to single versions
  galaxy.yml
Labels: enhancement

#104 Use infra__security_group_vpce_name as variable for VPC Endpoint SG
  roles/infrastructure/tasks/setup_aws_network.yml
Labels: bug

#106 Fix failed_when condition for GCP Service Accounts Policies
  roles/platform/tasks/teardown_gcp_authz.yml
Labels: bug

#110 Update parameters for EC2 module
  galaxy.yml
  roles/infrastructure/tasks/setup_aws_compute.yml
Labels: bug
