Repository cloudera-labs/cloudera.exe, pull requests merged in 2023-03, with the labels that each got.

#118 Added subnet filters to the df_service module.
  docs/configuration.yml
  roles/runtime/defaults/main.yml
  roles/runtime/tasks/initialize_base.yml
  roles/runtime/tasks/setup_base.yml
Labels: enhancement

#137 Fixing regression due to recent changes to DataFlow runtime.
  roles/runtime/tasks/initialize_teardown.yml
  roles/runtime/tasks/teardown_base.yml
Labels: bug

#111 RAZ Implementation for Azure
  docs/configuration.yml
  roles/common/defaults/main.yml
  roles/platform/defaults/main.yml
  roles/platform/tasks/initialize_azure.yml
  roles/platform/tasks/initialize_teardown_azure.yml
  roles/platform/tasks/setup_azure_authz.yml
  roles/platform/tasks/setup_azure_datalake.yml
  roles/platform/tasks/setup_azure_idbroker.yml
  roles/platform/tasks/teardown_azure_authz.yml
  roles/platform/vars/main.yml
Labels: enhancement, validated
