Repository cloudera-labs/cloudera.exe, pull requests merged in 2025-08, with the labels that each got.

#206 Update version to 3.0.0-rc1
  galaxy.yml
Labels: validated, skip

#208 Update prometheus role for ansible-lint, argument specs, and README
  roles/prometheus/README.md
  roles/prometheus/defaults/main.yml
  roles/prometheus/handlers/main.yml
  roles/prometheus/meta/argument_specs.yml
  roles/prometheus/tasks/main.yml
Labels: bug, documentation, validated

#212 Update mount role for ansible-lint, argument specs, and README
  roles/mount/README.md
  roles/mount/defaults/main.yml
  roles/mount/meta/argument_specs.yml
  roles/mount/meta/main.yml
  roles/mount/tasks/main.yml
  roles/mount/tasks/volume.yml
Labels: enhancement, validated

#213 Update playbooks for ansible-lint
  playbooks/pvc_base_postfix.yml
  playbooks/pvc_base_prereqs_ext.yml
  playbooks/pvc_base_teardown.yml
Labels: bug, validated

#216 Add pgAdmin installation role
  roles/pgadmin/README.md
  roles/pgadmin/defaults/main.yml
  roles/pgadmin/handlers/main.yml
  roles/pgadmin/meta/argument_specs.yml
  roles/pgadmin/molecule/default/converge.yml
  roles/pgadmin/molecule/default/create.yml
  roles/pgadmin/molecule/default/destroy.yml
  roles/pgadmin/molecule/default/molecule.yml
  roles/pgadmin/molecule/default/prepare.yml
  roles/pgadmin/molecule/default/requirements.yml
  roles/pgadmin/molecule/default/verify.yml
  roles/pgadmin/tasks/main.yml
  roles/pgadmin/templates/pgadmin-db-servers.json.j2
  roles/pgadmin/templates/pgadmin-docker-compose.yml.j2
  roles/pgadmin/templates/pgadmin-service.j2
  roles/pgadmin/vars/main.yml
Labels: enhancement, validated

#218 Add AMD ROCm drivers installation role
  roles/rocm/README.md
  roles/rocm/defaults/main.yml
  roles/rocm/handlers/main.yml
  roles/rocm/meta/argument_specs.yml
  roles/rocm/molecule/default/converge.yml
  roles/rocm/molecule/default/create.yml
  roles/rocm/molecule/default/destroy.yml
  roles/rocm/molecule/default/molecule.yml
  roles/rocm/molecule/default/prepare.yml
  roles/rocm/molecule/default/requirements.yml
  roles/rocm/molecule/default/verify.yml
  roles/rocm/tasks/RedHat-post.yml
  roles/rocm/tasks/RedHat-pre.yml
  roles/rocm/tasks/default.yml
  roles/rocm/tasks/main.yml
  roles/rocm/vars/RedHat.yml
  roles/rocm/vars/default.yml
Labels: enhancement, validated

#222 Add PostgreSQL client installation role
  roles/postgresql_client/README.md
  roles/postgresql_client/defaults/main.yml
  roles/postgresql_client/meta/argument_specs.yml
  roles/postgresql_client/molecule/default/converge.yml
  roles/postgresql_client/molecule/default/create.yml
  roles/postgresql_client/molecule/default/destroy.yml
  roles/postgresql_client/molecule/default/molecule.yml
  roles/postgresql_client/molecule/default/prepare.yml
  roles/postgresql_client/molecule/default/requirements.yml
  roles/postgresql_client/molecule/default/verify.yml
  roles/postgresql_client/tasks/main.yml
Labels: enhancement, validated

#225 Add CSD installation role
  roles/cm_csd/README.md
  roles/cm_csd/defaults/main.yml
  roles/cm_csd/meta/argument_specs.yml
  roles/cm_csd/molecule/default/converge.yml
  roles/cm_csd/molecule/default/create.yml
  roles/cm_csd/molecule/default/destroy.yml
  roles/cm_csd/molecule/default/molecule.yml
  roles/cm_csd/molecule/default/prepare.yml
  roles/cm_csd/molecule/default/requirements.yml
  roles/cm_csd/molecule/default/verify.yml
  roles/cm_csd/tasks/main.yml
Labels: enhancement, validated

#226 Add CM server installation role
  roles/cm_server/README.md
  roles/cm_server/defaults/main.yml
  roles/cm_server/handlers/main.yml
  roles/cm_server/library/cm_prepare_db.py
  roles/cm_server/meta/argument_specs.yml
  roles/cm_server/molecule/default/converge.yml
  roles/cm_server/molecule/default/create.yml
  roles/cm_server/molecule/default/destroy.yml
  roles/cm_server/molecule/default/molecule.yml
  roles/cm_server/molecule/default/prepare.yml
  roles/cm_server/molecule/default/requirements.yml
  roles/cm_server/molecule/default/verify.yml
  roles/cm_server/tasks/main.yml
Labels: enhancement

#227 Add CM agent installation role
  roles/cm_agent/README.md
  roles/cm_agent/defaults/main.yml
  roles/cm_agent/handlers/main.yml
  roles/cm_agent/meta/argument_specs.yml
  roles/cm_agent/molecule/default/converge.yml
  roles/cm_agent/molecule/default/create.yml
  roles/cm_agent/molecule/default/destroy.yml
  roles/cm_agent/molecule/default/molecule.yml
  roles/cm_agent/molecule/default/prepare.yml
  roles/cm_agent/molecule/default/requirements.yml
  roles/cm_agent/molecule/default/verify.yml
  roles/cm_agent/tasks/main.yml
Labels: enhancement, validated

#229 Add deprecation module for legacy roles
  plugins/modules/deprecation.py
Labels: enhancement, validated

#230 Deprecate auto_repo_mirror role
  .ansible-lint-ignore
  meta/runtime.yml
  roles/auto_repo_mirror/README.md
  roles/auto_repo_mirror/tasks/inject.yml
  roles/auto_repo_mirror/tasks/parse_definition_for_mirror_targets.yml
  roles/auto_repo_mirror/tasks/populate_from_upstream.yml
  roles/auto_repo_mirror/tasks/prepare_auto_repo_mirror.yml
  roles/auto_repo_mirror/tasks/update_mirror_cache.yml
Labels: validated, deprecated

#236 Deprecate infrastructure role
  .ansible-lint-ignore
  meta/runtime.yml
  roles/infrastructure/meta/main.yml
  roles/infrastructure/tasks/main.yml
Labels: validated, deprecated

#237 Deprecate init_deployment role
  .ansible-lint-ignore
  meta/runtime.yml
  roles/init_deployment/tasks/main.yml
Labels: validated, deprecated

#240 Deprecate rdbms.client and rdbms.server roles
  .ansible-lint-ignore
  meta/runtime.yml
  roles/rdbms/client/mysql_connector/tasks/main.yml
  roles/rdbms/client/oracle_connector/tasks/main.yml
  roles/rdbms/client/postgresql_connector/tasks/main.yml
  roles/rdbms/server/tasks/main.yml
Labels: validated, deprecated

#241 Deprecate rdbms_server role
  .ansible-lint-ignore
  meta/runtime.yml
  roles/rdbms_server/meta/main.yml
  roles/rdbms_server/tasks/main.yml
Labels: validated, deprecated

#242 Deprecate runtime role
  .ansible-lint-ignore
  meta/runtime.yml
  roles/runtime/meta/main.yml
  roles/runtime/tasks/main.yml
Labels: validated, deprecated

#244 Fix documentation reference to external FreeIPA role
  roles/freeipa_server/meta/argument_specs.yml
Labels: documentation, validated, skip

#245 Relocate role plugins
  plugins/modules/cm_prepare_db.py
  plugins/modules/jdk_facts.py
  roles/cm_server/tasks/main.yml
  roles/prereq_jdk/tasks/main.yml
Labels: bug, validated, skip

#248 Fix cm_version filter relocation
  plugins/filter/cm_version.py
  roles/cm_repo/vars/RedHat-CM5.yml
  roles/cm_repo/vars/RedHat-CM6.yml
  roles/cm_repo/vars/RedHat.yml
Labels: skip

#250 Fix FreeIPA client packages management
  roles/freeipa_client/defaults/main.yml
  roles/freeipa_client/handlers/main.yml
  roles/freeipa_client/meta/argument_specs.yml
  roles/freeipa_client/molecule/default/converge.yml
  roles/freeipa_client/molecule/default/create.yml
  roles/freeipa_client/molecule/default/destroy.yml
  roles/freeipa_client/molecule/default/molecule.yml
  roles/freeipa_client/molecule/default/prepare.yml
  roles/freeipa_client/molecule/default/requirements.yml
  roles/freeipa_client/molecule/default/verify.yml
  roles/freeipa_client/tasks/main.yml
  roles/freeipa_client/vars/main.yml
Labels: skip

#251 Fix FreeIPA server packages management
  roles/freeipa_server/README.md
  roles/freeipa_server/defaults/main.yml
  roles/freeipa_server/handlers/main.yml
  roles/freeipa_server/meta/argument_specs.yml
  roles/freeipa_server/molecule/default/converge.yml
  roles/freeipa_server/molecule/default/create.yml
  roles/freeipa_server/molecule/default/destroy.yml
  roles/freeipa_server/molecule/default/molecule.yml
  roles/freeipa_server/molecule/default/prepare.yml
  roles/freeipa_server/molecule/default/requirements.yml
  roles/freeipa_server/molecule/default/verify.yml
  roles/freeipa_server/tasks/main.yml
Labels: skip

#254 Fix PostgreSQL server GPG key URL for RedHat
  roles/postgresql_server/tasks/RedHat_pre.yml
Labels: skip

#246 Add module to query Cloudera support matrix
  plugins/modules/supported.py
Labels: enhancement, validated

#257 Add FreeIPA DNS for ECS role
  roles/freeipa_server_ecs/README.md
  roles/freeipa_server_ecs/defaults/main.yml
  roles/freeipa_server_ecs/meta/argument_specs.yml
  roles/freeipa_server_ecs/molecule/default/converge.yml
  roles/freeipa_server_ecs/molecule/default/create.yml
  roles/freeipa_server_ecs/molecule/default/destroy.yml
  roles/freeipa_server_ecs/molecule/default/molecule.yml
  roles/freeipa_server_ecs/molecule/default/prepare.yml
  roles/freeipa_server_ecs/molecule/default/requirements.yml
  roles/freeipa_server_ecs/molecule/default/verify.yml
  roles/freeipa_server_ecs/tasks/main.yml
Labels: enhancement, validated

#258 Add FreeIPA users role
  roles/freeipa_server_users/README.md
  roles/freeipa_server_users/defaults/main.yml
  roles/freeipa_server_users/meta/argument_specs.yml
  roles/freeipa_server_users/molecule/default/converge.yml
  roles/freeipa_server_users/molecule/default/create.yml
  roles/freeipa_server_users/molecule/default/destroy.yml
  roles/freeipa_server_users/molecule/default/molecule.yml
  roles/freeipa_server_users/molecule/default/prepare.yml
  roles/freeipa_server_users/molecule/default/requirements.yml
  roles/freeipa_server_users/molecule/default/verify.yml
  roles/freeipa_server_users/tasks/main.yml
Labels: enhancement, validated

#260 Update prereq_jdk role to validate Manager and Runtime versions
  plugins/modules/jdk_facts.py
  roles/prereq_jdk/README.md
  roles/prereq_jdk/defaults/main.yml
  roles/prereq_jdk/meta/argument_specs.yml
  roles/prereq_jdk/tasks/main.yml
  roles/prereq_jdk/vars/main.yml
Labels: enhancement, validated

#262 Add raw_filters parameter to supported lookup and module
  plugins/lookup/supported.py
  plugins/module_utils/cldr_supported.py
  plugins/modules/supported.py
Labels: enhancement, validated

#266 Add unit tests for cloudera.exe.jdk_facts
  tests/unit/conftest.py
  tests/unit/plugins/modules/jdk_facts/test_jdk_facts.py
Labels: enhancement, validated

#268 Update API docs and fix linting issues
  plugins/filter/version.yml
  plugins/modules/cm_prepare_db.py
  plugins/modules/deprecation.py
  plugins/modules/jdk_facts.py
  roles/prereq_database/meta/argument_specs.yml
Labels: documentation, enhancement, validated

#272 Add variables to skip of overlap check for FreeIPA server DNS zones
  roles/freeipa_server/defaults/main.yml
  roles/freeipa_server/meta/argument_specs.yml
  roles/freeipa_server/tasks/main.yml
Labels: enhancement, validated

#273 Update support matrix lookup maps for Rocky
  roles/cm_repo/vars/main.yml
  roles/prereq_python/tasks/main.yml
  roles/prereq_python/vars/main.yml
  roles/prereq_supported/vars/main.yml
Labels: enhancement, validated

#269 Update version_added to roles, modules, and plugins
  plugins/filter/combine_onto.yml
  plugins/lookup/supported.py
  plugins/test/version.yml
  roles/auto_repo_mirror/meta/argument_specs.yml
  roles/blackbox/meta/argument_specs.yml
  roles/blackbox_exporter/meta/argument_specs.yml
  roles/common/meta/argument_specs.yml
  roles/data/meta/argument_specs.yml
  roles/dynamic_inventory/meta/argument_specs.yml
  roles/freeipa_client/meta/argument_specs.yml
  roles/freeipa_host_group/meta/argument_specs.yml
  roles/freeipa_server/meta/argument_specs.yml
  roles/grafana/meta/argument_specs.yml
  roles/info/meta/argument_specs.yml
  roles/infrastructure/meta/argument_specs.yml
  roles/init_deployment/meta/argument_specs.yml
  roles/mount/meta/argument_specs.yml
  roles/node_exporter/meta/argument_specs.yml
  roles/nodeexporter/meta/argument_specs.yml
  roles/platform/meta/argument_specs.yml
  roles/prometheus/meta/argument_specs.yml
  roles/provision/meta/argument_specs.yml
  roles/rdbms/client/mysql_connector/meta/argument_specs.yml
  roles/rdbms/client/oracle_connector/meta/argument_specs.yml
  roles/rdbms/client/postgresql_connector/meta/argument_specs.yml
  roles/rdbms/server/meta/argument_specs.yml
  roles/rdbms_server/meta/argument_specs.yml
  roles/runtime/meta/argument_specs.yml
  roles/sequence/meta/argument_specs.yml
  roles/sudoers/meta/argument_specs.yml
  roles/sudoers/tasks/main.yml
  roles/sudoers/tasks/teardown.yml
  roles/tls_fetch_ca_certs/meta/argument_specs.yml
  roles/tls_generate_csr/meta/argument_specs.yml
  roles/tls_install_certs/meta/argument_specs.yml
  roles/tls_signing/meta/argument_specs.yml
Labels: enhancement, validated

#271 Add changelog
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  changelogs/config.yaml
  galaxy.yml
  pyproject.toml
  roles/sudoers/meta/main.yml
Labels: documentation, enhancement

#275 Fix prereq_cloudera_users references
  roles/prereq_cloudera_manager/meta/argument_specs.yml
  roles/prereq_ecs/meta/argument_specs.yml
Labels: documentation, skip

#190 Update deprecated actions
  .github/workflows/label_pr.yml
  .github/workflows/reset_pr.yml
  .github/workflows/validate_pr.yml
Labels: enhancement, validated

#276 Add cloudera_manager_release parameter
  roles/cm_repo/README.md
  roles/cm_repo/defaults/main.yml
  roles/cm_repo/filter_plugins/semantic_version.py
  roles/cm_repo/meta/argument_specs.yml
  roles/cm_repo/tasks/main.yml
  roles/cm_repo/vars/RedHat-CM5.yml
  roles/cm_repo/vars/RedHat-CM6.yml
  roles/cm_repo/vars/RedHat.yml
Labels: enhancement, validated

#277 Add yamllint config
  .yamllint
  roles/auto_repo_mirror/tasks/parse_definition_for_mirror_targets.yml
  roles/auto_repo_mirror/tasks/update_mirror_cache.yml
  roles/infrastructure/tasks/initialize_teardown_aws.yml
  roles/infrastructure/tasks/setup_aws_network.yml
  roles/infrastructure/tasks/setup_aws_storage.yml
  roles/infrastructure/tasks/teardown_aws_network.yml
Labels: enhancement, validated

#278 Remove comments from cm_repo tasks
  roles/cm_repo/tasks/main.yml
Labels: skip

#280 Update testing instructions
  TESTING.md
  tests/integration/integration_config.yml.template
  tests/integration/requirements.txt
  tests/integration/targets/exec_cdp/aliases
  tests/integration/targets/exec_cdp/meta/main.yml
  tests/integration/targets/exec_cdp/tasks/main.yml
  tests/integration/targets/light_duty_l1/aliases
  tests/integration/targets/light_duty_l1/tasks/main.yml
  tests/integration/targets/light_duty_l1/vars/cdp.yml
  tests/integration/targets/medium_duty_l1/aliases
  tests/integration/targets/medium_duty_l1/tasks/main.yml
  tests/integration/targets/medium_duty_l1/vars/cdp.yml
  tests/integration/targets/setup_infra/aliases
  tests/integration/targets/setup_infra/meta/main.yml
  tests/integration/targets/setup_infra/tasks/main.yml
  tests/integration/targets/setup_infra/vars/infra.yml
  tests/integration/targets/teardown_infra/aliases
  tests/integration/targets/teardown_infra/meta/main.yml
  tests/integration/targets/teardown_infra/tasks/main.yml
  tests/integration/targets/teardown_infra/vars/infra.yml
  tests/integration/test_molecule_integration.py
  tests/unit/conftest.py
  tests/unit/plugins/modules/jdk_facts/test_jdk_facts.py
Labels: documentation, enhancement, validated

#281 Update README for 3.0.0
  README.md
Labels: documentation, enhancement, validated

#283 Update dependent actions for publish_docs.yml workflow
  .github/workflows/publish_docs.yml
Labels: validated, skip_changelog

#286 Add Umami metrics header to docs
  docsbuild/conf.py
  docsbuild/templates/layout.html
Labels: documentation, enhancement
